insert into courses (title, study_year) values ('Electrodynamics', 6);
insert into courses (title, study_year) values ('Labor protection', 6);
insert into courses (title, study_year) values ('C Programming', 2);
insert into courses (title, study_year) values ('Algebra', 1);
insert into courses (title, study_year) values ('Functional Analysis', 6);
insert into courses (title, study_year) values ('Electrodynamics', 3);
insert into courses (title, study_year) values ('Quantum Electrodynamics', 2);
insert into courses (title, study_year) values ('Quantum Mechanics', 1);
insert into courses (title, study_year) values ('Theory of Relativity', 4);
insert into courses (title, study_year) values ('Algebra', 6);
insert into courses (title, study_year) values ('Database Development', 6);
insert into courses (title, study_year) values ('Algorithms and Data Structures', 6);
insert into courses (title, study_year) values ('Software Engineering', 5);
insert into courses (title, study_year) values ('Programming in Cobol', 2);
insert into courses (title, study_year) values ('Algorithms and Data Structures', 4);
insert into courses (title, study_year) values ('Programming in Javascript', 3);
insert into courses (title, study_year) values ('C++ Programming', 3);
insert into courses (title, study_year) values ('Algebra', 4);
insert into courses (title, study_year) values ('Programming in OCAML', 4);
insert into courses (title, study_year) values ('Programming in OCAML', 1);
insert into courses (title, study_year) values ('Atomic Physics', 2);
insert into courses (title, study_year) values ('Physics', 1);
insert into courses (title, study_year) values ('Atomic Physics', 6);
insert into courses (title, study_year) values ('Descriptive Geometry', 2);
insert into courses (title, study_year) values ('History of programming', 1);
insert into courses (title, study_year) values ('Software Engineering', 3);
insert into courses (title, study_year) values ('Theory of Relativity', 1);
insert into courses (title, study_year) values ('Database Development', 4);
insert into courses (title, study_year) values ('Development of user interfaces', 2);
insert into courses (title, study_year) values ('Analytical Geometry', 3);
insert into courses (title, study_year) values ('Safety', 3);
insert into courses (title, study_year) values ('History of programming', 3);
insert into courses (title, study_year) values ('Languages ​​and Grammar', 4);
insert into courses (title, study_year) values ('Programming in Cobol', 4);
insert into courses (title, study_year) values ('Programming with Fortran', 3);
insert into courses (title, study_year) values ('Theory of Relativity', 5);
insert into courses (title, study_year) values ('Functional Analysis', 2);
insert into courses (title, study_year) values ('Programming in C#', 5);
insert into courses (title, study_year) values ('Electrodynamics', 1);
insert into courses (title, study_year) values ('C Programming', 6);
insert into courses (title, study_year) values ('Programming in F#', 6);
insert into courses (title, study_year) values ('Software Engineering', 2);
insert into courses (title, study_year) values ('Practical Physics', 2);
